name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'YAY!, This is your first issue. Can you solve it? Go for it and make your first PR.'' first issue'
        pr-message: 'Hurray Your first PR is submitted, Love from : Vidit :'' first pr'
